---
- name: debian | Installing DRBD packages
  apt:
    name: "{{ drbd_deb_packages }}"
    state: present
  become: true

- name: debian | Installing Heartbeat Package
  apt:
    name: heartbeat
    state: present
  become: true
  when: drbd_use_heartbeat
